### ISSUE TITLE
AsignarController

### ISSUE THREAD

**Issue by jorgecabrera** [renzoavil17/meteoro#6]
No pareciera ser un controlador que aporte funcionalidad a la aplicacion o sea necesario, quizas seria conveniente borrarlo, o trasladar su funcionalidad a otro gsp

**Comment by jorgecabrera** [comment]
Lo mismo parece pasar con ProductosController el controlador productos no hace nada

**Comment by ballegretti** [comment]
Fue eliminado AsignarController.
El ProductosController es utilizado. Está referenciado en buscar.gsp y se utiliza para pasar a productos.gsp y enviar el parámetro id empleado.
